RunAsync supports Task<T> running a Function
JYCabello/DeFuncto pull request #18
Opened 2021-07-12 17:49 UTC by theonlyroboboro

2021-07-12 17:51 UTC, theonlyroboboro commented
@JYCabello Can you help me with the Test? Not sure if you like it when i'm adding testframeworks

2021-07-13 05:24 UTC, JYCabello commented
@theonlyroboboro Just hit it, worst that can happen is that we have a discussion, I don't see a downside.

2021-07-13 05:25 UTC, JYCabello commented
Also, should we move all `RunAsync` overloads to the `Tasks` extensions file?

2021-07-13 06:23 UTC, theonlyroboboro commented
@JYCabello Created the test and moved it to the Task extension

2021-07-13 06:51 UTC, JYCabello requested changes

2021-07-13 06:51 UTC, JYCabello commented on src/DeFuncto.Core/DeFuncto.Core.csproj
> +      <PackageVersion>0.2.3</PackageVersion>
Bump the assertions library too.

2021-07-13 06:51 UTC, JYCabello commented on src/DeFuncto.Core/Extensions/Tasks.cs
> +        public static Task<T> RunAsync<T>(this T self, Func<T, Task> f) => self.Apply(async t =>
Since you moved these, move the tests in the test project to match the new structure.

2021-07-13 06:51 UTC, JYCabello commented on src/DeFuncto.Tests/Core/Extensions/Tasks/RunAsync.cs
> +            await witness.RunAsync(async w => w.Touch());
Holy, this checks are quite cool.
Reintroduce the pragmas.
Perhaps only inside the lambdas. try and see if it can be done.

2021-07-13 06:55 UTC, JYCabello commented
Always remember to reference the issue you are solving.

2021-07-13 07:26 UTC, JYCabello approved these changes

2021-07-13 08:35 UTC, merged