Run, RunAsync and  Iter return Unit
JYCabello/DeFuncto pull request #34
Opened 2021-07-25 18:47 UTC by theonlyroboboro

closes #28

2021-07-26 07:25 UTC, JYCabello requested changes
It's also for `Result` and `AsyncResult`

2021-07-26 07:25 UTC, JYCabello commented on src/DeFuncto.Core/Types/AsyncOption.cs
> +        public Task<Option<Unit>> Iter(Action<T> f) =>
Task<Unit>

2021-07-26 07:25 UTC, JYCabello commented on src/DeFuncto.Tests/Core/Extensions/Objects/Run.cs
> +                .Run(w => w.Touch());
Reintroduce the other .Run, they are different overloads and both were tested

2021-07-26 17:02 UTC, JYCabello requested changes
It's still missing the `Iter` in `Result` and `AsyncResult`

2021-07-28 07:24 UTC, theonlyroboboro commented
@JYCabello fixt

2021-07-28 12:45 UTC, JYCabello approved these changes

2021-07-28 13:01 UTC, merged