Added Equals to Result
JYCabello/DeFuncto pull request #43
Opened 2021-09-20 12:17 UTC by theonlyroboboro

2021-09-20 12:24 UTC, theonlyroboboro commented
partial #35

2021-09-20 12:55 UTC, JYCabello approved these changes

2021-09-20 12:55 UTC, JYCabello commented on src/DeFuncto.Core/Types/Result.cs
> +            IsOk == other.IsOk && other.value.Equals(value);
The IsOk is implicitly tested in the equals of the `Du`, just test the equality of the DU.

2021-09-21 06:26 UTC, JYCabello requested changes

2021-09-21 06:26 UTC, JYCabello commented on src/DeFuncto.Core/Types/Result.cs
> +            var nval = obj as Result<TOk, TError>?;
Look at the version with pattern matching in `Du`

2021-09-21 06:26 UTC, JYCabello commented on src/DeFuncto.Tests/Core/Types/Result/GetHashCode.cs
> +using static DeFuncto.Prelude;
Static imports last.

2021-09-21 06:26 UTC, JYCabello commented on src/DeFuncto.Tests/Core/Types/Result/Equals.cs
> +using static DeFuncto.Prelude;
Static imports last.

2021-09-22 06:35 UTC, JYCabello approved these changes

2021-09-22 07:29 UTC, merged